env:
  browser: true
  es2021: true
extends:
  - 'plugin:vue/essential'
  - 'eslint:recommended'
overrides:
  - files: ["server*", "server/*"]
    env:
      node: true
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - vue
rules:
  arrow-spacing: ["warn"]
  block-spacing: ["off"]
  camelcase: ["off"]
  curly: ["off"]
  dot-notation: ["warn"]
  eqeqeq: ["warn", "smart"]
  indent: ["off", 2, { "SwitchCase": 1 }]
  no-callback-literal: ["off"]
  no-cond-assign: ["warn"]
  no-multi-spaces: ["off"]
  no-tabs: ["off"]
  no-trailing-space: ["off"]
  no-trailing-spaces: ["off"]
  no-var: ["off"]
  object-curly-spacing: ["off"]
  quote-props: ["off"]
  quotes: ["off", "double", {"avoidEscape": true}]
  semi: ["warn", "never"]
  space-before-blocks: ["off"]
  space-before-function-paren: ["off"]
  space-infix-ops: ["warn"]
  yoda: ["off", "never", { "exceptRange": true }]
  vue/require-component-is: ["off"]
